version: "3.8"

services:
    service_node:
        container_name: class_ci-cd
        restart: always
        image: ${DOCKER_USERNAME}/class_ci-cd:latest
        ports:
            - "${PORT_CONFIG}" # Sử dụng biến môi trường từ PowerShell truyền vào
        env_file:
            - .env
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        networks:
            - class_ci-cd  

networks:
    class_ci-cd:
        driver: bridge
